language: node_js
node_js:
  - 12
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - pnpm config set store-dir ~/.pnpm-store
services:
  - mongodb
install:
  - pnpm install -g serverless
  - pnpm install
script:
  - pnpm test
  - sls deploy